- name: setup
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_pkg_mgr }}.yml"
    - "default.yml"
  tags: always

- include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family | lower }}.yml"
    - "default.yml"
  tags:
    - bootstrap
    - bootstrap_node
    - install
    - install_node
    - update
    - update_node

- name: Install node modules
  npm:
    name: "{{ item.name | default(item) }}"
    global: "{{ node_global_install }}"
    path: "{{ node_modules_path }}"
  with_items: "{{ node_modules }}"
  tags:
    - bootstrap
    - bootstrap_node
    - install
    - install_node
    - update
    - update_node
