---

- block:
    - name: package | install npm
      package: name="{{ node_name }}" state=present

    - name: npm | node_modules
      npm:
        name: "{{ item }}"
        state: "{{ install_state }}"
        global: "{{ node_global_install }}"
        path: "{{ node_modules_path }}"
      with_items: "{{ node_modules }}"

    - name: package | uninstall npm
      package: name="{{ node_name }}" state=absent
      when: install_state == 'absent'
  tags:
    - bootstrap
    - install
    - update
