---

- block:
    - name: package | npm
      package: name="{{ node_name }}" state="{{ install_state }}"

    - name: npm | node_modules
      npm:
        name: "{{ item }}"
        state: "{{ install_state }}"
        global: "{{ node_global_install }}"
        path: "{{ node_modules_path | default(omit) }}"
      with_items: "{{ node_modules }}"
  tags:
    - bootstrap
    - install
    - update
